# numpy

In [3]:
import numpy as np

print(np.__version__)

2.0.2


Array(배열)
- 다차원배열
- 배열의 속성
- 배열의 자료형(Data Type)
- 배열 함수와 생성함수
- Shape 변환 함수
- 배열의 형태(Shape)와 축(Axis) 지정
- 인덱싱, 슬라이싱
- 산술연산과 Broadcasting(브로드캐스팅)

In [34]:
d1 = [1,2,'3',4,5]
a1 = np.array(d1)
print(a1)
print(type(a1), a1.shape, a1.dtype, a1.itemsize)

['1' '2' '3' '4' '5']
<class 'numpy.ndarray'> (5,) <U21 84


In [33]:
d2 = [[1,2,7],[3,4,8],[5,6,9]]
a2 = np.array(d2)
print(a2)
print(type(a2), a2.shape, a2.dtype, a2.itemsize)

[[1 2 7]
 [3 4 8]
 [5 6 9]]
<class 'numpy.ndarray'> (3, 3) int64 8


In [38]:
d6 = [[1,2,3,4],[5,6],[7,8,9]]
print(d6)
# a6 = np.array(a6)
# print(type(a6), a6.shape, a6.dtype)

[[1, 2, 3, 4], [5, 6], [7, 8, 9]]


In [42]:
d7 = [[1,2,3],[4,5,6],[7,8,9]]
a7 = np.array(d7)
print(a7[0,2], a7[1,0], a7[2,1])

3 4 8


In [67]:
d8 = list(range(1,13))
a8_1 = np.array(d8)
print(a8_1)
a8_2 = np.array(d8).reshape(2,6)
print(a8_2)
a8_3 = np.array(d8).reshape(3,2,2)
print(a8_3)

print(a8_1.shape, a8_2.shape, a8_3.shape)
print(a8_1.ndim, a8_2.ndim, a8_3.ndim) # 차원

print(a8_3[0][1][0])

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
(12,) (2, 6) (3, 2, 2)
1 2 3
3


In [85]:
a9 = np.arange(1,7).reshape(2,3)
print(a9, a9.dtype)
a9 = a9.astype(np.float64)
print(a9, a9.dtype)
a9 = a9.astype(int)
print(a9, a9.dtype)
a9 = a9.astype(float)
print(a9, a9.dtype)
a9 = a9.astype(str)
print(a9, a9.dtype, a9.itemsize)
# a9 = a9.astype(np.string_) 2.0이상 버전에서 제거됨
a9 = a9.astype(np.bytes_)
print(a9, a9.dtype, a9.itemsize)
a9 = a9.astype(np.str_)
print(a9, a9.dtype, a9.itemsize)

[[1 2 3]
 [4 5 6]] int64
[[1. 2. 3.]
 [4. 5. 6.]] float64
[[1 2 3]
 [4 5 6]] int64
[[1. 2. 3.]
 [4. 5. 6.]] float64
[['1.0' '2.0' '3.0']
 ['4.0' '5.0' '6.0']] <U32 128
[[b'1.0' b'2.0' b'3.0']
 [b'4.0' b'5.0' b'6.0']] |S32 32
[['1.0' '2.0' '3.0']
 ['4.0' '5.0' '6.0']] <U32 128


In [95]:
a1 = np.arange(1,26).reshape(5,5)
print(a1)

print(a1[2][2], a1[2,2])
print(a1[1:-1])
print(a1[1:-1, 1:-1])
print(a1[3:, :3])
print(a1[:1, -1:])

a2 = np.ones(9)
print(a2)
a2 = np.ones(9).reshape(3,3)
print(a2)

a3 = np.zeros(9).reshape(3,3)
print(a3)
a3 = np.eye(5)
print(a3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
13 13
[[ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
[[16 17 18]
 [21 22 23]]
[[5]]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [97]:
a4 = np.arange(1,7).reshape(2,3)
print(a4)

a5 = np.transpose(a4)
print(a5)

a6 = a5.T
print(a6)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]


In [106]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([10,20])
a3 = np.array([3,4])

print(a2+1)
print(a2-30)
print(a2 *10)
print(a2 / 2)
print(100 / a2)
print("---------------------")
print(a1+1)
print(a1-30)
print(a1 *10)
print(a1 / 2)
print(100 / a1)
print("---------------------")
print(a2+a3)
print(a1+a2)
print(a1*a2)


[11 21]
[-20 -10]
[100 200]
[ 5. 10.]
[10.  5.]
---------------------
[[2 3]
 [4 5]]
[[-29 -28]
 [-27 -26]]
[[10 20]
 [30 40]]
[[0.5 1. ]
 [1.5 2. ]]
[[100.          50.        ]
 [ 33.33333333  25.        ]]
---------------------
[13 24]
[[11 22]
 [13 24]]
[[10 40]
 [30 80]]


In [108]:
a3 = np.array([[1,2],[3,4]])
a4 = np.array([[2,3],[4,5]])

print(a3+a4)
print(a3*a4)
print(np.matmul(a3,a4)) # 행렬 곱

a5 = np.arange(1,101)
print(a5.max(), a5.min(), a5.mean(), a5.sum())

a5 = np.arange(1,101).reshape(10,10)
print(a5.max(), a5.min(), a5.mean(), a5.sum())

[[3 5]
 [7 9]]
[[ 2  6]
 [12 20]]
[[10 13]
 [22 29]]
100 1 50.5 5050
100 1 50.5 5050
