# 넘파이(numpy)

[NumPy](https://numpy.org/)
- ndarray 객체, 다차원 배열
- **넘파이**는 메모리를 효율적으로 사용하기 위해 하나의 타입만 들어갈 수 있음
  - cf. **리스트**는 여러가지 타입이 들어갈 수 있음(숫자와 문자)

- Numpy란
  - Numerical Python의 약자.
  - 다차원 배열을 효율적으로 처리하고 쉽게 사용할 수 있도록하는 파이썬 라이브러리.
  - 데이터 구조 외에도 수치 계산을 위해 효율적으로 구현된 기능을 제공.
  - 파이썬으로 진행하는 데이터 분석과 인공지능 학습에 있어 가장 필수적인 라이브러리.
  - 파이썬의 List에 비해 빠르고, 메모리를 효율적으로 사용.
  - 반복문 없이 배열의 처리를 지원하므로 빠르고 편리함.

In [1]:
import numpy as np
print(np.__version__)

2.0.2


Array(배열)
  - 다차원 배열
  - 배열의 속성
  - 배열의 자료형(Data Type)
  - 배열 함수와 생성함수
  - Shape 변환 함수
  - 배열의 형태(Shape)와 축(Axis) 지정
  - 인덱싱(Indexing), 슬라이싱(Slicing)
  - 산술연산과 Broadcasting(브로드캐스팅)  


- ndarray 객체
  - N-dimensional Array의 약자.
  - ndarray객체는 넘파이에서 다차원 배열을 의미.
  - 모든 원소가 같은 자료형이어야 한다.
  - 한 번 생성된 배열은 원소의 개수 변결 불가.

In [2]:
d1 = [1,2,'3',4,5]
print(type(d1),type(d1[1]),type(d1[2]))

<class 'list'> <class 'int'> <class 'str'>


In [7]:
a1 = np.array(d1)
print(a1)
print(type(a1),a1.shape,a1.dtype,a1.itemsize)

['1' '2' '3' '4' '5']
<class 'numpy.ndarray'> (5,) <U21 84


In [5]:
d2 = [1,2,3,4,5]
a2 = np.array(d2)
print(type(a2),a2.shape,a2.dtype,a2.itemsize)

<class 'numpy.ndarray'> (5,) int64 8


In [8]:
d3 = [[1,2],[3,4],[5,6]]
a3 = np.array(d3)
print(type(a3),a3.shape,a3.dtype,a3.itemsize)
print(a3)

<class 'numpy.ndarray'> (3, 2) int64 8
[[1 2]
 [3 4]
 [5 6]]


In [9]:
d4 = [[1,2,3],[4,5,6.0]]
a4 = np.array(d4)
print(a4)
print(type(a4),a4.shape, a4.dtype,a4.itemsize)

[[1. 2. 3.]
 [4. 5. 6.]]
<class 'numpy.ndarray'> (2, 3) float64 8


In [10]:
d5 = [[1,2,3],[4,5,6],[7,8,9]]
a5 = np.array(d5)
print(a5)
print(type(a5),a5.shape, a5.dtype,a5.itemsize)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'> (3, 3) int64 8


In [12]:
d6 = [[1,2,3,4],[5,6],[7,8,9]]

# a6 = np.array(d6)
# print(a6)
# print(type(a6),a6.shape, a6.dtype)
print(d6)

[[1, 2, 3, 4], [5, 6], [7, 8, 9]]


In [13]:
d7 = [[1,2,3],[4,5,6],[7,8,9]]
a7 = np.array(d7)
print(a7)

# 3 4 8  출력
print(a7[0][2],a7[1][0],a7[2][1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3 4 8


- 형변환 처리

In [14]:
d8 = list(range(1,13))
d8
a8_1 = np.array(d8)
print(a8_1)
a8_2 = np.array(d8).reshape(2,6)
print(a8_2)
a8_3 = np.array(d8).reshape(3,2,2)
print(a8_3)

print(a8_1.shape,a8_2.shape,a8_3.shape)
print(a8_1.ndim,a8_2.ndim,a8_3.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
(12,) (2, 6) (3, 2, 2)
1 2 3


In [15]:
# 3 8 11 출력
print(a8_3[0][1][0],a8_3[1][1][1],a8_3[2][1][0])

3 8 11


- a9 = a9.astype(np.string_) #<String
- 이 오류는 np.string_ 데이터 타입이 NumPy 2.0 릴리스에서 제거되었기 때문에 발생.
- 이제 대신 np.bytes_를 사용해야 함.

In [17]:
a9 = np.arange(1,7).reshape(2,3)
print(a9,a9.dtype)
a9 = a9.astype(np.float64)
print(a9,a9.dtype)
a9 = a9.astype('int32')
print(a9,a9.dtype)
a9 = a9.astype('float64')
print(a9,a9.dtype)
a9 = a9.astype('str') #<U32
print(a9,a9.dtype,a9.itemsize)

# a9 = a9.astype(np.string_) #<String
a9 = a9.astype(np.bytes_) #<String
print(a9,a9.dtype,a9.itemsize)

a9 = a9.astype(np.str_) #<U32
print(a9,a9.dtype,a9.itemsize)

[[1 2 3]
 [4 5 6]] int64
[[1. 2. 3.]
 [4. 5. 6.]] float64
[[1 2 3]
 [4 5 6]] int32
[[1. 2. 3.]
 [4. 5. 6.]] float64
[['1.0' '2.0' '3.0']
 ['4.0' '5.0' '6.0']] <U32 128
[[b'1.0' b'2.0' b'3.0']
 [b'4.0' b'5.0' b'6.0']] |S32 32
[['1.0' '2.0' '3.0']
 ['4.0' '5.0' '6.0']] <U32 128


- 함수들
  - np.arrange()
  - np.ones()
  - np.linspace()
  - np.zeros()
  - np.full()

In [7]:
a1 = np.arange(1,26).reshape(5,5)
print(a1)

print(a1[2][2], a1[2,2])
print(a1[1:-1])
print(a1[1:-1,1:-1])
print(a1[3:,:3])
print(a1[:1,-1:])

a2 = np.ones(9)
print(a2)

a2 = np.ones(9).reshape(3,3)
print(a2)

a3 = np.zeros(9).reshape(3,3)
print(a3)

a3 = np.eye(5)
print(a3)

# 주어진 구간을 균일한 간격으로 나눈다..
# np.linspace(시작, 끝, 개수).
# 시작과 끝을 포함해서 지정된 개수만큼 균일한 간격으로 숫자를 채움.
a4 = np.linspace(0, 4, 5)
print(a4)

# 주어진 형태의 배열을 만들고, 모두 주어진 값으로 채움.
a5 = np.full((2,3),0.5)
print(a5)

# ones_like(), zeros_like() 함수
# 인수로 지정된 배열 객체의 형태(shape)와 같은 형태의 배열을 생성하고 초기화.
a6 = np.array([[1, 2], [3, 4]])
print(a6.shape)
a7 = np.zeros_like(a6)
print(a7, a7.shape)
a8 = np.ones_like(a6)
print(a8, a8.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
13 13
[[ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
[[16 17 18]
 [21 22 23]]
[[5]]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[0. 1. 2. 3. 4.]
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]]
(2, 2)
[[0 0]
 [0 0]] (2, 2)
[[1 1]
 [1 1]] (2, 2)


- 배열(Array)의 축(Axis)

In [2]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])
y = np.array([[1, 2, 3, 4, 5]])
z = np.array([[1], [2], [3], [4], [5]])
print(x.shape, y.shape, z.shape)

(5,) (1, 5) (5, 1)


- 전치행렬(transpose matrix) :
  - 행렬의 행과 열을 바꾸기, 행렬의 축을 바꾸는 방법

In [19]:
a4 = np.arange(1,7).reshape(2,3)
print(a4)

a5 = np.transpose(a4)
print(a5)

a6 = a5.T
print(a6)


[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]


- 연산

In [20]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([10,20])
a3 = np.array([3,4])

print(a2 + 1)
print(a2 - 30)
print(a2 * 10)
print(a2 / 2)
print(100 / a2)

print(a1 + 1)
print(a1 - 30)
print(a1 * 10)
print(a1 / 2)
print(100 / a1)

print(a2 + a3)
print(a1 + a2)

print(a1 * a2)

[11 21]
[-20 -10]
[100 200]
[ 5. 10.]
[10.  5.]
[[2 3]
 [4 5]]
[[-29 -28]
 [-27 -26]]
[[10 20]
 [30 40]]
[[0.5 1. ]
 [1.5 2. ]]
[[100.          50.        ]
 [ 33.33333333  25.        ]]
[13 24]
[[11 22]
 [13 24]]
[[10 40]
 [30 80]]


- 행렬곱 : matmul( , )

In [21]:
a3 = np.array([[1,2],[3,4]])
a4 = np.array([[2,3],[4,5]])

print(a3 + a4)
print(a3 * a4)
print(np.matmul(a3,a4)) # 행렬 곱

a5 = np.arange(1,101)
print(a5.max(),a5.min(),a5.mean(),a5.sum())

a5 = np.arange(1,101).reshape(10,10)
print(a5.max(),a5.min(),a5.mean(),a5.sum())


[[3 5]
 [7 9]]
[[ 2  6]
 [12 20]]
[[10 13]
 [22 29]]
100 1 50.5 5050
100 1 50.5 5050
